version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: apae
      MYSQL_USER: apae_user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - mysql_network

volumes:
  mysql_data:
    driver: local

networks:
  mysql_network:
    driver: bridge
