name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Webhook para a VM
        run: |
          curl -X POST http://35.247.231.143:4000/webhook
